### PR TITLE
Use git from wandisco repositories on centos 7

### PR DESCRIPTION
**Pull request by rockdreamer**
The version provided by this repository fixes an issue reported by teamcity (it will no longer support the older version provided on centos 7 in the future) and visual studio code

### CODE REVIEW

**Comment by siong-chin** [comment]
How does the package provided by wandisco compare to those provided by endpoint or IUS?

**Comment by rockdreamer** [comment]
the wandisco binaries substitute the system git, which is what I'm explicitly after :)

**Comment by siong-chin** [comment]
Yes, endpoint and IUS also provides up-to-date git packages. Just wondering why you chose wandisco?

**Comment by rockdreamer** [comment]
> Yes, endpoint and IUS also provides up-to-date git packages. Just wondering why you chose wandisco?

two reasons:
- how many packages are present in the repository
- does the system git package get replaced or is it an additional git executable in a different position?

Looking at [endpoint](https://packages.endpoint.com/rhel/7/os/x86_64/) and [ius](https://repo.ius.io/7/x86_64/packages/) and comparing to [wandisco](http://opensource.wandisco.com/centos/7/git/x86_64/), wandisco has a git-specific repo, a more up-to-date git version and replaces the system git package.

**Review by siong-chin — APPROVED** [review]

**Pull request merged**
